# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
use_frameworks!

target 'TestHekrSDK' do

	
	pod 'HekrApiSDK', :path => '../SDK_3.3_framework2'
	pod 'Masonry'

end
